### DISCUSSION TITLE
simplify running couchdb-docker in single-node mode

### DISCUSSION THREAD

**Discussion by jkhsjdhjs** [apache/couchdb#2948] [Ideas]
Hello,

at work we're using gitlab ci to test a project. The project supports couchdb as a database backend, that's why we're also running tests on it.
However, since couchdb doesn't run in single-node mode, required databases like `_users` or `_replicator` are not created automatically. That's (probably) why the setup of couchdb doesn't complete successfully and eventually times out: https://gist.github.com/jkhsjdhjs/203d7c762a05d9cbf2b11757911def3a
The gitlab ci test configuration is the following:
```yml
test:
  stage: test
  only: [branches, tags, merge_requests]
  inherit:
    variables: ["PIP_CACHE_DIR"]
  variables:
    COUCHDB_USER: "admin"
    COUCHDB_PASSWORD: "yo0Quai3"
  services:
    - couchdb:2.3
  script:
    - [... test commands ...]
```

Single-node mode can only be enabled with a config file, which has be placed or mounted inside the docker container. That's why @wohali proposed the following for the gitlab ci configuration:
```bash
echo "[couchdb]" >10-single-node.ini
echo "single_node=true" >> 10-single-node.ini
docker run -p 5984:5984 -v /path/to/10-single-node.ini:/opt/couchdb/etc/local.d/10-single-node.ini apache/couchdb:3.1.0
```
While I'm convinced this would work, for it to work inside the gitlab ci runner, we'd have to change the image to something that includes the `docker` command (we're currently using `python:3.6`).
And even with `gitlab/dind` - an image, that includes docker - I couldn't get it to work (TBF I didn't test further after it failed the first time). See https://github.com/apache/couchdb-docker/issues/54#issuecomment-643822973

I also asked in `#gitlab` on freenode for a solution, the only suggestion there was to maintain my own fork of couchdb-docker in single-node mode, or to build a single-node docker image as part of the pipeline.

Because there seems to be no easy solution to this for me, I suggest adding a `COUCHDB_SINGLE_NODE` environment variable to couchdb-docker, which is set to `false` or `0` by default to preserve existing behavior.

I'd like to hear your opinion on this, and if you have other ideas to solve this issue, please let me hear them!
