### DISCUSSION TITLE
How to setup couchdb cluster with docker `compose.yaml`

### DISCUSSION THREAD

**Discussion by grey4owl** [apache/couchdb#4975] [Q&A]
Hi,

I'm trying to setup couchdb cluster of 2 nodes with `compose.yaml` file

```yaml
version: '3'
services:
  node-1:
    container_name: test-node-1
    image: couchdb
    restart: always
    ports:
      - '6001:5984'
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password1
      - NODENAME=node-1
      - COUCHDB_SECRET=my_secret_key
      - ERL_FLAGS=-setcookie mycookie
    volumes:
      - ./dbdata1:/opt/couchdb/data

  node-2:
    container_name: test-node-2
    image: couchdb
    restart: always
    ports:
      - '6002:5984'
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password2
      - NODENAME=node-2
      - COUCHDB_SECRET=my_secret_key
      - COUCHDB_JOIN=node-1
      - ERL_FLAGS=-setcookie mycookie
    volumes:
      - ./dbdata2:/opt/couchdb/data
```

and when i run `docker compose up -d` everything started working except when i check nodes with `curl http://admin:password@server_ip:5984/_membership` i get the following output:

```json
{
    "all_nodes":
         ["couchdb@node-1"],
    "cluster_nodes":
         ["couchdb@node-1"]
}
```

and also `curl http://admin:password@server_ip:5984/_cluster_setup`  should be `{"state":"cluster_finished"}` but i got `cluster_enabled`

What am i missing?
