### ISSUE TITLE
Running CouchDB in container with limited CPU makes creation of views crash 

### ISSUE THREAD

**Issue by aclarembeau** [apache/couchdb#1297]
Hi, when I run a couchdb container with limited CPU, the creation of a view always crashes (either using the REST api or the futon interface).  

## Expected Behavior
The view should be created without any message. 

## Current Behavior
When I create the view, after 5 seconds (the default value of the os_timeout): I have a `unknown error` message. 

## Steps to Reproduce (for bugs)

Create a docker-compose.yml file with: 

# version of docker-compose files
version: "3"

```
services:
  db:
    image: couchdb:latest
    ports: ["9980:5984"] 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
```

Run it with `docker-compose up`
Using the futon interface (127.0.0.1:9980), create a database & a document. 
Then, try to create a view, you'll get the `unknown error message` due to a "system timeout". 

When you remove the limits of CPU and memory usage, everything seems to work well. 

## Your Environment
Fedora release 26 (Twenty Six)
Result of `uname -a`: `Linux localhost.localdomain 4.15.6-200.fc26.x86_64 #1 SMP Mon Feb 26 18:51:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* Version used: Latest version on docker hub as of 26/02
