### ISSUE TITLE
CouchDB API Cluster with Docker Compose

### ISSUE THREAD

**Issue by JohnOllhorn** [apache/couchdb#1634]
I give it up soon to use on CouchDB!

I've been trying for days to get CouchDB to run in a Docker Compose environment...

```json
{"error":"bad_request","reason":"Add node failed. Invalid Host and/or Port."}
```

How do I get more nodes into an existing cluster through the API?

Which ports need to be opened in Docker-Compose? 5984, 5986, 4369 AND 9100-9200 ??? xD

(Please do not link this article: http://docs.couchdb.org/en/stable/cluster/setup.html)

Is my Docker Config wrong?

```yml
  couchdb-0:
    container_name: couchdb-0
    hostname: ${COUCHDB_0_HOST}
    domainname: ${DOMAIN_NAME}
    image: couchdb:latest
    volumes:
      - couchdb-0:/opt/couchdb/data
    ports: ['${COUCHDB_0_HTTP}:5984','${COUCHDB_0_NODEAPI}:5986','${COUCHDB_0_HTTPS}:6984']
    networks:
      couchdb_cluster: { aliases: ['${COUCHDB_0_HOST}.${DOMAIN_NAME}'] }
    environment:
      NODENAME: ${COUCHDB_0_HOST}.${DOMAIN_NAME}
      COUCHDB_USER: ${COUCHDB_0_USER}
      COUCHDB_PASSWORD: ${COUCHDB_0_PASSWORD}
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_COOKIE: ${DOMAIN_NAME}
    restart: always
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  couchdb-1:
    container_name: couchdb-1
    hostname: ${COUCHDB_1_HOST}
    domainname: ${DOMAIN_NAME}
    image: couchdb:latest
    volumes:
      - couchdb-1:/opt/couchdb/data
    ports: ['${COUCHDB_1_HTTP}:5984','${COUCHDB_1_NODEAPI}:5986','${COUCHDB_1_HTTPS}:6984']
    networks:
      couchdb_cluster: { aliases: ['${COUCHDB_1_HOST}.${DOMAIN_NAME}'] }
    environment:
      NODENAME: ${COUCHDB_1_HOST}.${DOMAIN_NAME}
      COUCHDB_USER: ${COUCHDB_1_USER}
      COUCHDB_PASSWORD: ${COUCHDB_1_PASSWORD}
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_COOKIE: ${DOMAIN_NAME}
      COUCHDB_SYNC_ADMINS_NODE: ${COUCHDB_0_HOST}.${DOMAIN_NAME}
    restart: always
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  couchdb-2:
    container_name: couchdb-2
    hostname: ${COUCHDB_2_HOST}
    domainname: ${DOMAIN_NAME}
    image: couchdb:latest
    volumes:
      - couchdb-2:/opt/couchdb/data
    ports: ['${COUCHDB_2_HTTP}:5984','${COUCHDB_2_NODEAPI}:5986','${COUCHDB_2_HTTPS}:6984']
    networks:
      couchdb_cluster: { aliases: ['${COUCHDB_2_HOST}.${DOMAIN_NAME}'] }
    environment:
      NODENAME: ${COUCHDB_2_HOST}.${DOMAIN_NAME}
      COUCHDB_USER: ${COUCHDB_2_USER}
      COUCHDB_PASSWORD: ${COUCHDB_2_PASSWORD}
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_COOKIE: ${DOMAIN_NAME}
      COUCHDB_SYNC_ADMINS_NODE: ${COUCHDB_0_HOST}.${DOMAIN_NAME}
    restart: always
```
