### ISSUE TITLE
Unable to mount config file to CouchDB 2.3.0 in Kubernetes from ConfigMap (file ownership problem)!

### ISSUE THREAD

**Issue by kvzhkv** [apache/couchdb#1926]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I'm trying to set up CouchDB 2.3.0 in single node mode in Kubernetes cluster.
It is unable to mount config file (for example `local.ini` in `/opt/couchdb/etc`) in Kubernetes. Apparently, it is file permission/ownership problem.
Pod starts and crashes immediately without any logs!!! 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

deployment.yaml
```
apiVersion: v1
kind: Pod
metadata:
    name: couchdb
    namespace: db
spec:
            containers:
              - name: couchdb
                image: couchdb:2.3.0
                ports:
                    - containerPort: 5984
                volumeMounts:
                    - mountPath: /opt/couchdb/etc/local.ini
                      subPath: local.ini
                      name: couchdb-config
                livenessProbe:
                    httpGet:
                        path: /_up
                        port: 5984
                    initialDelaySeconds: 10
                    timeoutSeconds: 1
                    failureThreshold: 3
                    periodSeconds: 5
            volumes:
                - name: couchdb-config
                  configMap:
                    name: couchdb-config
```

configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
    name: couchdb-config
    namespace: db
data:
    local.ini: |
        [vhosts]
        example.com = /test-db/_design/api/_rewrite
```

I found out that when I mount `local.ini` file it owned by `root` user and not by `couchdb` as other files in `etc` folder.

```
drwxr-xr-x 1 couchdb couchdb  4096 Feb  6 05:18 default.d
-rw-r----- 1 couchdb couchdb 22345 Nov 29 18:48 default.ini
drwxr-xr-x 2 couchdb couchdb  4096 Feb  6 05:17 local.d
-rw-r--r-- 1 root    root       80 Feb 20 09:58 local.ini
-rw-rw-r-- 1 couchdb couchdb   968 Feb  6 05:17 vm.args
```

But for CouchDB 2.2.0 this is not a problem. It successfully starts with the same manifest.

Are there any workarounds or solutions of this issue?
