### ISSUE TITLE
Can't start v.3.0.0 in docker

### ISSUE THREAD

**Issue by pavellzubkov** [apache/couchdb#2603]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I get 

> ERROR: CouchDB 3.0+ will no longer run in "Admin Party

i've try apache/couchdb:3.0  apache/couchdb:3.0.0 apache/couchdb:3 images

## Steps to Reproduce

my docker-compose section
```
version: '3'

services:
  db:        
        image: apache/couchdb:3.0
        restart: always   
        volumes: 
            - ./etc:/opt/couchdb/etc/local.d  
            - ./data:/opt/couchdb/data
            - ./log:/opt/couchdb/var/log
        ports:
          - "5984:5984"
``` 
in ./etc/local.ini

```
[admins]
;admin = mysecretpassword
admin = -hashed-6d3c30241ba0aaa4e16c6ea99224f915687ed8cd,7f4a3e05e0cbc6f48a0035e3508eef90

```

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
normal start

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.0.0
* Browser name and version: 
* Operating system and version: win10 with docker desktop
* Arch: AMD (Ryzen 7 3700u)

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by pavellzubkov** [comment]
adding to compose 'environment ' section solved problem
```
 db:        
        image: apache/couchdb:3.0
        restart: always   
        volumes: 
            - ./etc:/opt/couchdb/etc/local.d  
            - ./data:/opt/couchdb/data
            - ./log:/opt/couchdb/var/log
        ports:
          - "5984:5984"
        environment:
          - 'COUCHDB_USER=admin'
          - 'COUCHDB_PASSWORD=password' 
```
strange ... local.ini not checking for admins? though so v 2.3.1 have same behaviour

**Comment by git-AlexS** [comment]
Same problem here, also struggling to solve this any way other than setting the environment variables. Why is this issue closed? Isn't it preferable to use the in-built password hashing in the .ini files?

**Comment by kernerdev** [comment]
I still have the same problem :/

**Comment by praveen-ap** [comment]
I have this problem too...

**Comment by benel** [comment]
> ```yaml 
> environment:
>   - 'COUCHDB_USER=admin'
>   - 'COUCHDB_PASSWORD=password' 

@pavellzubkov, did you try also without the quotes?

Personally I use:

```yaml
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
```

**Comment by pavellzubkov** [comment]
@benel, @praveen-ap , @kernerdev , @git-AlexS   huh) it is funny bug. i try right now with latest official image 3.3.2 version.
my docker compose -
```
version: '3'

services:
  db:
    image: couchdb:3.3.2
    restart: always
    volumes:
      - ./etc:/opt/couchdb/etc/local.d
      - ./data:/opt/couchdb/data
      - ./log:/opt/couchdb/var/log  
    ports:
      - "5984:5984"    
```
local.ini admins part
```
[admins]
admin = -pbkdf2-468e5ac6817f98582967e49b0ee08f407786917d,b4ceba9e6d3f7c7f8f63e16a5b7ab533,10
; admin = -pbkdf2-40bdd84d22425e3b8419548b73eff92cb721bf7c,17682ea8c1f9a5342dadf8d5f94a8407,10
```
if write like above - then all work fine, but if local.ini contain commented row after [admins] then couch db fail to start with admin party error.

this don't work - 
```
[admins]
; admin = -pbkdf2-40bdd84d22425e3b8419548b73eff92cb721bf7c,17682ea8c1f9a5342dadf8d5f94a8407,10
admin = -pbkdf2-468e5ac6817f98582967e49b0ee08f407786917d,b4ceba9e6d3f7c7f8f63e16a5b7ab533,10
```
this work fine without environment var admin -
```
[admins]
admin = -pbkdf2-468e5ac6817f98582967e49b0ee08f407786917d,b4ceba9e6d3f7c7f8f63e16a5b7ab533,10
; admin = -pbkdf2-40bdd84d22425e3b8419548b73eff92cb721bf7c,17682ea8c1f9a5342dadf8d5f94a8407,10
```
