### ISSUE TITLE
Couchdb 3 with Clouseau on Docker?

### ISSUE THREAD

**Issue by pavellzubkov** [apache/couchdb#2604]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
is there a way to run couchdb 3.0.0 with full text search on docker?
some example docker-compose file or couchdb image with includes clouseau?
yesterday i try to run apache/couchdb:3.0 image and it seems to be work

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by willholley** [comment]
There is a ticket in relation to this at https://github.com/apache/couchdb-docker/issues/8. I'm not particularly experienced with Docker Compose but the issue is that Clouseau and CouchDB need to share the same loopback network if running in different containers. This works on Kubernetes when both containers are in the same pod - I don't know if there's a way to do it in Docker Compose.

Another option is to use a combined container which includes both components. IBM publish one [here](https://hub.docker.com/r/ibmcom/couchdb3).

**Comment by pavellzubkov** [comment]
thank you! 
ibmcom/couchdb3 image useful for playground with full text search. but this image can't open databases created by apache/couchdb:3.0 image.
my docker compose file
```
version: '3'

services:
  db:
        #ibmcom/couchdb3 treehouses/couchdb:2.3.1 apache/couchdb:3.0
        image: ibmcom/couchdb3
        restart: always   
        volumes: 
            - ./etc:/opt/couchdb/etc/local.d  
            - ./data:/opt/couchdb/data
            - ./log:/opt/couchdb/var/log
        ports:
          - "5984:5984"
        environment:
          - 'COUCHDB_USER=admin'
          - 'COUCHDB_PASSWORD=password'
```
